/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema;

import br.com.jmary.home.Home;
import java.awt.BorderLayout;
import java.awt.Component;
import utilidades.JOPM;

/**
 *
 * @author pc
 */
public class Sistema_Home extends javax.swing.JPanel {

    public Home Home;
    
    /**
     * Creates new form Fonema_E_Letra_Home
     * @param Home2
     */
    public Sistema_Home( Home Home2 ) {
        initComponents();
        
        Home = Home2;
        
        Sistema_Home_Inicio Inicio = new Sistema_Home_Inicio( this );
    }
            
    public void adicionarSubmenu( Component c ) {
        try{
            
            // Adicionar Submenu Fonema e letra
            Home.Home_JPanel_Norte.removeAll();
            Home.Home_JPanel_Norte.add( c, BorderLayout.NORTH );
            c.setVisible( true );
            Home.validate();
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
                + e.getMessage() + "\n", "Sistema_Home" ); }
    }
    
    public void retirarSubmenu() {
        try{
            
            // Adicionar Submenu Fonema e letra
            Home.Home_JPanel_Norte.removeAll();
            Home.validate();
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
                + e.getMessage() + "\n", "Sistema_Home" ); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
