/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package clientes;

import br.com.jmary.home.Home;
import javax.swing.JTabbedPane;
import venda_new.Venda_New;
import venda_search.Menu_Pesquisa_Venda;

/**
 *
 * @author pc
 */
public class Clientes_Home extends javax.swing.JPanel {

    public Home                                   Home;
    public JTabbedPane                            tabHome;
    
    public Clientes_Home_Inicio       Inicio;
            
    /**
     * Creates new form Fonema_E_Letra_Home
     * @param Home2
     */
    public Clientes_Home( Home Home2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
                                        
        Inicio = new Clientes_Home_Inicio( this );
                
    }
    
    //////////////////////////////////////////////////////    
    public Clientes_Home( Home Home2, JTabbedPane tabHome2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = tabHome2;
                                
        Inicio = new Clientes_Home_Inicio( this, tabHome );
                
    }
    //////////////////////////////////////////////////////
    
     //////////////////////////////////////////////////////
    public Menu_Pesquisa_Venda Menu_Pesquisa_Venda;
    
    public Clientes_Home( Home Home2, Menu_Pesquisa_Venda Menu_Pesquisa_Venda2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
        
        Menu_Pesquisa_Venda = Menu_Pesquisa_Venda2;
                                
        Inicio = new Clientes_Home_Inicio( this, Menu_Pesquisa_Venda2 );
                
    }
    //////////////////////////////////////////////////////
    
    //////////////////////////////////////////////////////
    public Venda_New Venda_New;
    
    public Clientes_Home( Home Home2, Venda_New Venda_New2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
        
        Venda_New                 = Venda_New2;
                                
        Inicio = new Clientes_Home_Inicio( this, Venda_New2 );
                
    }
    //////////////////////////////////////////////////////
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHome = new javax.swing.JPanel();

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel pnHome;
    // End of variables declaration//GEN-END:variables
    
}
