/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_barra_menu;

import sistema.Sistema_Home;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import sistema_submenus.Submenu1;
import sistema_submenus.Submenu2;
import sistema_submenus.Submenu3;

/**
 *
 * @author AnaMariana
 */
public class Sistema_Barra_Menu extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    
    Sistema_Home  Sistema_Home;
    
    Alterar_Seta_Submenu Alterar_Seta_Submenu;

    /**
     * Creates new form PnHomeDesigner
     * @param Fonema_E_Letra_Home2
     */
    public Sistema_Barra_Menu( Sistema_Home Fonema_E_Letra_Home2 ) {
        initComponents();
        ((BasicInternalFrameUI)Fonema_E_Letra_Frame_Interno.getUI()).setNorthPane(null); //retirar o painel superior 
        
        Sistema_Home  = Fonema_E_Letra_Home2;
        
        //Habilita troca de seta
        Alterar_Seta_Submenu = new Alterar_Seta_Submenu( Sistema_Home );
                        
        inicio();
    }
    
    private void inicio(){
        
        mnConfiguracoes.setVisible(false);
        
        Sistema_Home.Home.Home_Frame_Interno.setJMenuBar( Fonema_E_Letra_Barra_Menu );               
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fonema_E_Letra_Frame_Interno = new javax.swing.JInternalFrame();
        Fonema_E_Letra_Barra_Menu = new javax.swing.JMenuBar();
        menu_seta = new javax.swing.JMenu();
        menu_Ajuda = new javax.swing.JMenu();
        menu_Ajuda1 = new javax.swing.JMenu();
        menu_Ajuda3 = new javax.swing.JMenu();
        menu_Ajuda2 = new javax.swing.JMenu();
        mnConfiguracoes = new javax.swing.JMenu();
        mniMateria = new javax.swing.JMenuItem();
        mniCategoria = new javax.swing.JMenuItem();
        mniSubcategoria = new javax.swing.JMenuItem();
        mniAssunto = new javax.swing.JMenuItem();
        mniExercicios = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniBanco_de_Dados = new javax.swing.JMenuItem();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Fonema_E_Letra_Frame_Interno.setBorder(null);
        Fonema_E_Letra_Frame_Interno.setVisible(true);

        menu_seta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_imagens/seta_para_cima.png"))); // NOI18N
        menu_seta.setToolTipText("Ocultar Submenu");
        menu_seta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_setaMousePressed(evt);
            }
        });
        Fonema_E_Letra_Barra_Menu.add(menu_seta);

        menu_Ajuda.setText("Ajuda");
        Fonema_E_Letra_Barra_Menu.add(menu_Ajuda);

        menu_Ajuda1.setText("Clientes");
        menu_Ajuda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_Ajuda1MousePressed(evt);
            }
        });
        Fonema_E_Letra_Barra_Menu.add(menu_Ajuda1);

        menu_Ajuda3.setText("Produtos");
        menu_Ajuda3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_Ajuda3MousePressed(evt);
            }
        });
        Fonema_E_Letra_Barra_Menu.add(menu_Ajuda3);

        menu_Ajuda2.setText("Nova Venda");
        menu_Ajuda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_Ajuda2MousePressed(evt);
            }
        });
        Fonema_E_Letra_Barra_Menu.add(menu_Ajuda2);

        mnConfiguracoes.setText("Configurações");
        mnConfiguracoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnConfiguracoesMousePressed(evt);
            }
        });

        mniMateria.setText("Matéria");
        mniMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mniMateriaMousePressed(evt);
            }
        });
        mniMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMateriaActionPerformed(evt);
            }
        });
        mnConfiguracoes.add(mniMateria);

        mniCategoria.setText("Categoria");
        mniCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mniCategoriaMousePressed(evt);
            }
        });
        mnConfiguracoes.add(mniCategoria);

        mniSubcategoria.setText("Subcategoria");
        mniSubcategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mniSubcategoriaMousePressed(evt);
            }
        });
        mnConfiguracoes.add(mniSubcategoria);

        mniAssunto.setText("Assunto");
        mniAssunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mniAssuntoMousePressed(evt);
            }
        });
        mnConfiguracoes.add(mniAssunto);

        mniExercicios.setText("Exercícios");
        mniExercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mniExerciciosMousePressed(evt);
            }
        });
        mnConfiguracoes.add(mniExercicios);
        mnConfiguracoes.add(jSeparator4);

        mniBanco_de_Dados.setText("Banco de Dados");
        mnConfiguracoes.add(mniBanco_de_Dados);

        Fonema_E_Letra_Barra_Menu.add(mnConfiguracoes);

        Fonema_E_Letra_Frame_Interno.setJMenuBar(Fonema_E_Letra_Barra_Menu);

        javax.swing.GroupLayout Fonema_E_Letra_Frame_InternoLayout = new javax.swing.GroupLayout(Fonema_E_Letra_Frame_Interno.getContentPane());
        Fonema_E_Letra_Frame_Interno.getContentPane().setLayout(Fonema_E_Letra_Frame_InternoLayout);
        Fonema_E_Letra_Frame_InternoLayout.setHorizontalGroup(
            Fonema_E_Letra_Frame_InternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        Fonema_E_Letra_Frame_InternoLayout.setVerticalGroup(
            Fonema_E_Letra_Frame_InternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fonema_E_Letra_Frame_Interno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fonema_E_Letra_Frame_Interno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menu_setaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_setaMousePressed
        Alterar_Seta_Submenu.tabJanelaSubmenu( this.menu_seta );
    }//GEN-LAST:event_menu_setaMousePressed

    private void menu_Ajuda1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_Ajuda1MousePressed
        Sistema_Home.adicionarSubmenu(new Submenu1( Sistema_Home ) ); 
    }//GEN-LAST:event_menu_Ajuda1MousePressed

    private void menu_Ajuda2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_Ajuda2MousePressed
        Sistema_Home.adicionarSubmenu(new Submenu1( Sistema_Home ) ); 
    }//GEN-LAST:event_menu_Ajuda2MousePressed

    
    private void mniMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniMateriaActionPerformed

    private void mniMateriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniMateriaMousePressed
        Sistema_Home.Home.ControleTabs.AddTabsAoHome("Matérias", "/sistema_imagens/livroTp.gif", new materias.Materias_Home( Sistema_Home.Home ) ); 
    }//GEN-LAST:event_mniMateriaMousePressed

    private void mniCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniCategoriaMousePressed
        Sistema_Home.Home.ControleTabs.AddTabsAoHome("Categorias", "/sistema_imagens/livroTp.gif", new categorias.Categorias_Home( Sistema_Home.Home ) );  
    }//GEN-LAST:event_mniCategoriaMousePressed

    private void mniSubcategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniSubcategoriaMousePressed
        Sistema_Home.Home.ControleTabs.AddTabsAoHome("Subcategorias", "/sistema_imagens/livroTp.gif", new subcategoria.Subcategorias_Home( Sistema_Home.Home ) );  
    }//GEN-LAST:event_mniSubcategoriaMousePressed

    private void mniAssuntoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniAssuntoMousePressed
        Sistema_Home.Home.ControleTabs.AddTabsAoHome("Assunto", "/sistema_imagens/livroTp.gif", new assunto.Assunto_Home( Sistema_Home.Home ) );  
    }//GEN-LAST:event_mniAssuntoMousePressed

    private void mniExerciciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniExerciciosMousePressed
        Sistema_Home.Home.ControleTabs.AddTabsAoHome("Exercícios - Configurações", "/sistema_imagens/livroTp.gif", new exercicios.Exercicios_Home( Sistema_Home.Home ) );
    }//GEN-LAST:event_mniExerciciosMousePressed

    private void mnConfiguracoesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnConfiguracoesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnConfiguracoesMousePressed

    private void menu_Ajuda3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_Ajuda3MousePressed
        Sistema_Home.adicionarSubmenu(new Submenu1( Sistema_Home ) ); 
    }//GEN-LAST:event_menu_Ajuda3MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Fonema_E_Letra_Barra_Menu;
    private javax.swing.JInternalFrame Fonema_E_Letra_Frame_Interno;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu menu_Ajuda;
    private javax.swing.JMenu menu_Ajuda1;
    private javax.swing.JMenu menu_Ajuda2;
    private javax.swing.JMenu menu_Ajuda3;
    private javax.swing.JMenu menu_seta;
    private javax.swing.JMenu mnConfiguracoes;
    private javax.swing.JMenuItem mniAssunto;
    private javax.swing.JMenuItem mniBanco_de_Dados;
    private javax.swing.JMenuItem mniCategoria;
    private javax.swing.JMenuItem mniExercicios;
    private javax.swing.JMenuItem mniMateria;
    private javax.swing.JMenuItem mniSubcategoria;
    // End of variables declaration//GEN-END:variables
            
}
