/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package venda_new;

import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Pagamento_New extends javax.swing.JPanel {
    
    public Venda_New       Venda_New;
        
    /**
     * Creates new form Fonema_E_Letra_Home
     * @param Venda_New2
     */
    public Pagamento_New( Venda_New Venda_New2 ) {
        initComponents();
        
        Venda_New                       = Venda_New2;  
        
        lbValor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btEncerrar = new javax.swing.JButton();
        lbValor = new javax.swing.JLabel();

        jLabel1.setText("Valor pago pelo Cliente");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        btEncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/receber.png"))); // NOI18N
        btEncerrar.setText("Encerrar");
        btEncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btEncerrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btEncerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btEncerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String caracteres=".0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btEncerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEncerrarMousePressed
        if( !jTextField1.getText().trim().equals("") ) {
            
            float vPago = Float.parseFloat( jTextField1.getText().trim() );
            if( vPago >= Venda_New.vTotal ){
                
                jTextField1.setText( String.valueOf( vPago - Venda_New.vTotal ) );
                
                btEncerrar.setVisible(false);
                jLabel1.setText("TROCO");
                lbValor.setText("VENDA ENCERRADA");
                lbValor.setVisible(true);
                
                Venda_New.btSalvar.setVisible(false);
                Venda_New.lbEncerra.setText("VENDA ENCERRADA");
                Venda_New.salvarXX();
            }
            else{
                lbValor.setText("VALOR PAGO INVÁLIDO");
                lbValor.setVisible(true);
            }

        }
    }//GEN-LAST:event_btEncerrarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEncerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbValor;
    // End of variables declaration//GEN-END:variables
    
}
