/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package venda_new;

import clientes.Clientes;
import clientes.Clientes_Home;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jpa.DAOGenericoJPA;
import jpa.JPAUtil;
import print.ControleThread_Print;
import produtos.Produtos_Home;
import utilidades.JOPM;
import utilidades.OperacaoRealizada;
import venda.Venda_Home;

/**
 *
 * @author pc
 */
public class Venda_New extends javax.swing.JPanel {
    
    public float vTotal = 0;
    
    public Venda_Home              Venda_Home;
    public Venda_New_Inicio Inicio;
    
    public Clientes Clientes = new Clientes();
    public javax.swing.JTable tbPesquisa;
    public int IDSELECIONADA = -1;
    
    public int IDVENDARECEBIDA = -1;
    
    public Tabela_New_BD_Venda   Tabela_New_Pesquisa;

    /**
     * Creates new form Fornecedor_New
     * @param Venda_Home2
     */
    public Venda_New(Venda_Home Venda_Home2) {
        initComponents();
        
        btVisualizarImpressao.setVisible( false );
        btVisualizarImpressao1.setVisible( false );
        
        Venda_Home  = Venda_Home2;        
        tbPesquisa = new javax.swing.JTable();

        Tabela_New_Pesquisa      = new Tabela_New_BD_Venda( Venda_Home, this );
        Inicio     = new Venda_New_Inicio( this );
        
        inicio();
                
    }
    
    ///////////////////////////////////////////////////////////////////////////
    public Venda_New(Venda_Home Venda_Home2, Clientes Clientes2) {
        initComponents();
        
        btVisualizarImpressao.setVisible( false );
        btVisualizarImpressao1.setVisible( false );
        
        Venda_Home  = Venda_Home2;       
        Clientes    = Clientes2;
        tbPesquisa = new javax.swing.JTable();

        Tabela_New_Pesquisa      = new Tabela_New_BD_Venda( Venda_Home, this );
        Inicio     = new Venda_New_Inicio( this );
        
        inicio();
        
        tfClientes.setText(Clientes.getNome() );
                
    }
    ///////////////////////////////////////////////////////////////////////////
    
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public venda.Venda               Venda;
    public List<venda.Produtosdavenda> list_vendaprodutos;
    private boolean alterarX = false;
    public Venda_New(Venda_Home Venda_Home2, venda.Venda Venda2, List<venda.Produtosdavenda> list_vendaprodutos2, int IDVENDARECEBIDA2 ) {
        initComponents();        
        
        try{
            String v1 = String.valueOf( Venda.getTotal() );
            vTotal = Float.parseFloat(v1);
        }catch(Exception e ){} 
                
        btLixo.setEnabled(true);
                        
        alterarX = true;
        
        btVisualizarImpressao.setVisible( true );
        btVisualizarImpressao1.setVisible( true );
        
        IDVENDARECEBIDA = IDVENDARECEBIDA2;
        
        Venda              = Venda2;
        list_vendaprodutos = list_vendaprodutos2;
        
        Venda_Home  = Venda_Home2;        
        tbPesquisa = new javax.swing.JTable();

        Tabela_New_Pesquisa      = new Tabela_New_BD_Venda( Venda_Home, this );
        Inicio     = new Venda_New_Inicio( this, Venda2, list_vendaprodutos2 );
        
        inicio();
                
    }
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            
    private void inicio(){
        
        /*new Thread() {   @Override public void run() {*/ try { Thread.sleep( 1 ); 

            Venda_Home.Home.ControleTabs.AddTabSemSCControleNovo( tpTable, "Produtos", "/utilidades_imagens/carrinho.png", Tabela_New_Pesquisa );
                                    
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "inicio(), \n"
                + e.getMessage() + "\n", "Subcategorias_New_Inicio" ); } //} }.start();                 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpStatus1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btVisualizarImpressao = new javax.swing.JButton();
        btVisualizarImpressao1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btCancelar1 = new javax.swing.JButton();
        tfClientes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbFornecedor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbFornecedor1 = new javax.swing.JLabel();
        JPTble = new javax.swing.JPanel();
        tpTable = new javax.swing.JTabbedPane();
        jpLixo = new javax.swing.JPanel();
        btLixo = new javax.swing.JButton();
        jpLixo1 = new javax.swing.JPanel();
        tfTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbEncerra = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados da Venda");

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setEnabled(false);
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAtualizar.setEnabled(false);
        btAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAtualizarMousePressed(evt);
            }
        });

        btVisualizarImpressao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/printv2.png"))); // NOI18N
        btVisualizarImpressao.setText("Look");
        btVisualizarImpressao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVisualizarImpressao.setPreferredSize(new java.awt.Dimension(91, 27));
        btVisualizarImpressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarImpressaoActionPerformed(evt);
            }
        });

        btVisualizarImpressao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/printv.png"))); // NOI18N
        btVisualizarImpressao1.setText("Print");
        btVisualizarImpressao1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVisualizarImpressao1.setPreferredSize(new java.awt.Dimension(91, 27));
        btVisualizarImpressao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarImpressao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(btVisualizarImpressao1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVisualizarImpressao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar))
        );

        jpStatus1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAtualizar, btSalvar, btVisualizarImpressao, btVisualizarImpressao1});

        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAtualizar))
                    .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btVisualizarImpressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btVisualizarImpressao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jpStatus1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAtualizar, btSalvar, btVisualizarImpressao, btVisualizarImpressao1});

        btCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/selecionar.png"))); // NOI18N
        btCancelar1.setText("Selecionar");
        btCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancelar1.setPreferredSize(new java.awt.Dimension(96, 25));
        btCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCancelar1MousePressed(evt);
            }
        });
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });

        tfClientes.setEditable(false);
        tfClientes.setBackground(new java.awt.Color(255, 255, 255));
        tfClientes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfClientes.setPreferredSize(new java.awt.Dimension(195, 23));
        tfClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfClientesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfClientesMousePressed(evt);
            }
        });
        tfClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClientesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Cliente");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        lbFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/clienteos.gif"))); // NOI18N
        lbFornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        lbFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbFornecedorMousePressed(evt);
            }
        });

        jPanel3.setPreferredSize(new java.awt.Dimension(116, 57));

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/selecionar_produto.png"))); // NOI18N
        btAdicionar.setText("Selecionar");
        btAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdicionar.setPreferredSize(new java.awt.Dimension(96, 25));
        btAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAdicionarMousePressed(evt);
            }
        });
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Produto");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        lbFornecedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/carrinho.png"))); // NOI18N
        lbFornecedor1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        lbFornecedor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbFornecedor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbFornecedor1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbFornecedor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbFornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCancelar1, tfClientes});

        javax.swing.GroupLayout JPTbleLayout = new javax.swing.GroupLayout(JPTble);
        JPTble.setLayout(JPTbleLayout);
        JPTbleLayout.setHorizontalGroup(
            JPTbleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpTable)
        );
        JPTbleLayout.setVerticalGroup(
            JPTbleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpTable, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );

        btLixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/lixo2.png"))); // NOI18N
        btLixo.setToolTipText("Excluir");
        btLixo.setEnabled(false);
        btLixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLixoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpLixoLayout = new javax.swing.GroupLayout(jpLixo);
        jpLixo.setLayout(jpLixoLayout);
        jpLixoLayout.setHorizontalGroup(
            jpLixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLixoLayout.createSequentialGroup()
                .addComponent(btLixo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpLixoLayout.setVerticalGroup(
            jpLixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLixoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btLixo))
        );

        tfTotal.setEditable(false);
        tfTotal.setBackground(new java.awt.Color(255, 255, 255));
        tfTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotal.setPreferredSize(new java.awt.Dimension(65, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("TOTAL R$");

        javax.swing.GroupLayout jpLixo1Layout = new javax.swing.GroupLayout(jpLixo1);
        jpLixo1.setLayout(jpLixo1Layout);
        jpLixo1Layout.setHorizontalGroup(
            jpLixo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpLixo1Layout.setVerticalGroup(
            jpLixo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLixo1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbEncerra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbEncerra.setForeground(new java.awt.Color(255, 0, 0));
        lbEncerra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPTble, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jpLixo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpLixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbEncerra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(lbEncerra, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addComponent(jpStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpLixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpLixo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(JPTble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if( vTotal > 0 ){ 
            JOptionPane.showMessageDialog(this, new Pagamento_New(this) );
            /*
            btSalvar.setSelected(true);
            List<venda.Produtosdavenda> list2 = null;
            Inicio.salvar( new venda.Venda(), list2, false );   */
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    public void salvarXX() {                                         
        btSalvar.setSelected(true);
        List<venda.Produtosdavenda> list2 = null;
        Inicio.salvar( new venda.Venda(), list2, false );
    } 
    
    private void btAtualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtualizarMousePressed
        if( btAtualizar.isEnabled() == true ){
            
            //Inicio.setarCategorias( new categoria_do_produto.Categoriadoproduto() );
        }
    }//GEN-LAST:event_btAtualizarMousePressed

    private void tfClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClientesActionPerformed

    private void lbFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFornecedorMousePressed
        selecionarClientes();
    }//GEN-LAST:event_lbFornecedorMousePressed

    private void btCancelar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelar1MousePressed
        selecionarClientes();
    }//GEN-LAST:event_btCancelar1MousePressed

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void tfClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfClientesMouseEntered
        mouseEntra(tfClientes );
    }//GEN-LAST:event_tfClientesMouseEntered

    private void tfClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfClientesMouseExited
        mouseSai(tfClientes );
    }//GEN-LAST:event_tfClientesMouseExited

    private void tfClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfClientesMousePressed
        selecionarClientes();
    }//GEN-LAST:event_tfClientesMousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        selecionarClientes();
    }//GEN-LAST:event_jLabel5MousePressed

    private void btAdicionarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAdicionarMousePressed
        selecionarProduto();
    }//GEN-LAST:event_btAdicionarMousePressed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        selecionarProduto();
    }//GEN-LAST:event_jLabel6MousePressed

    private void lbFornecedor1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFornecedor1MousePressed
        selecionarProduto();
    }//GEN-LAST:event_lbFornecedor1MousePressed

    private void btVisualizarImpressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarImpressaoActionPerformed
        try{
            if( btVisualizarImpressao.isEnabled() == true ) {

                new Thread() {   @Override public void run() { try { Thread.sleep( 1 );  

                    //Imprimir_Home Imprimir = new Imprimir_Home( IDVENDARECEBIDA, Venda_Home.Home, Venda_Home.tabHome );
                            
                 } catch( Exception e ){ JOPM JOPM = new JOPM( 2, "eventoBotaoImprimir(), \n" + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
                        
            }
        } catch( Exception e ){ e.printStackTrace(); }
    }//GEN-LAST:event_btVisualizarImpressaoActionPerformed

    private void btLixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLixoActionPerformed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            if( btLixo.isEnabled() == true ) {
                
                if( Tabela_New_Pesquisa.tbPesquisa.getSelectedRow() != -1 ) {
                                                            
                    if( alterarX == true ){
                        
                        int                         m = Tabela_New_Pesquisa.tbPesquisa.getSelectedRow();
                        int id_GestorComprasProdutosX = (int) Tabela_New_Pesquisa.tbPesquisa.getValueAt( m, 0 );
                        //System.out.println("id_GestorComprasProdutosX - " + id_GestorComprasProdutosX);
                        
                        //////////////////////////////////////////////////////////////////////////////////////////
                        venda.Produtosdavenda Produtosdavenda = new venda.Produtosdavenda();
                    
                        Query qx = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOSDAVENDA WHERE ID = ?", venda.Produtosdavenda.class );
                        qx.setParameter(1, id_GestorComprasProdutosX );   

                        List<venda.Produtosdavenda> list = qx.getResultList();
                    
                        for (int i = 0; i < list.size(); i++){
                            Produtosdavenda = list.get(i);
                        } 
                    
                        DAOGenericoJPA DAOGenericoJPA = new DAOGenericoJPA( Produtosdavenda, JPAUtil.em()); 
                        DAOGenericoJPA.excluir();
                        ////////////////////////////////////////////////////////////////////////
                        double vTotalX = (Double) Tabela_New_Pesquisa.tbPesquisa.getValueAt( m, 3 );
                        if( !tfTotal.getText().trim().equals("") ){
                            vTotal = Float.parseFloat( tfTotal.getText().trim() );
                        }
                        else{
                            vTotal = 0;
                        }
                        vTotal -= vTotalX;
                        tfTotal.setText( String.valueOf( vTotal ) );
                        ////////////////////////////////////////////////////////////////////////
                        
                        Tabela_New_Pesquisa.tmPesquisa.removeRow( Tabela_New_Pesquisa.tbPesquisa.getSelectedRow() );                        
                        
                    }
                    else{
                        ////////////////////////////////////////////////////////////////////////
                        int                         m2 = Tabela_New_Pesquisa.tbPesquisa.getSelectedRow();
                        double vTotalX = (Double) Tabela_New_Pesquisa.tbPesquisa.getValueAt( m2, 3 );
                        vTotal -= vTotalX;
                        tfTotal.setText( String.valueOf( vTotal ) );
                        ////////////////////////////////////////////////////////////////////////
                        
                        Tabela_New_Pesquisa.tmPesquisa.removeRow( Tabela_New_Pesquisa.tbPesquisa.getSelectedRow() );                                                
                    }
                }
                else{
                    
                    JOPM JOPM = new JOPM( 2, "Nenhum ítem selecionado, \n"
                            + "Primeiro Selecione um" + 
                            "\nPara depois retirar/excluir" +
                            "\n", "Selecionar Ítem da Tabela" );
                }
                //System.out.println( "btLixoActionPerformed(java.awt.event.ActionEvent evt) - " + Tabela_New_Pesquisa.tbPesquisa.getSelectedRow() );
            }
        } catch( Exception e ){ e.printStackTrace(); } } }.start();            
    }//GEN-LAST:event_btLixoActionPerformed

    private void btVisualizarImpressao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarImpressao1ActionPerformed
        try{
            if( btVisualizarImpressao1.isEnabled() == true ) {
                
                new Thread() {   @Override public void run() { try { Thread.sleep( 1 );  
                     
                     ControleThread_Print t1 = new ControleThread_Print( IDVENDARECEBIDA );         
                     t1.setName("ControleThread_Print");           
                     t1.start();
                         
                } catch( Exception e ){ JOPM JOPM = new JOPM( 2, "eventoBotaoImprimir(), \n" + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
                        
            }
        } catch( Exception e ){ e.printStackTrace(); }
    }//GEN-LAST:event_btVisualizarImpressao1ActionPerformed

    int inVendaS = 0;
    public void imprimirXX( int id ) {  
        inVendaS = id;
        try{
            //if( btVisualizarImpressao1.isEnabled() == true ) {
                
                new Thread() {   @Override public void run() { try { Thread.sleep( 1 );  
                     Query q = null;
                     
                     ControleThread_Print t1 = new ControleThread_Print( inVendaS );         
                     t1.setName("ControleThread_Print");           
                     t1.start();
                         
                } catch( Exception e ){ JOPM JOPM = new JOPM( 2, "eventoBotaoImprimir(), \n" + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
                       
            //}
        } catch( Exception e ){ e.printStackTrace(); }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPTble;
    public javax.swing.JButton btAdicionar;
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btCancelar1;
    public javax.swing.JButton btLixo;
    public javax.swing.JButton btSalvar;
    public javax.swing.JButton btVisualizarImpressao;
    public javax.swing.JButton btVisualizarImpressao1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jpLixo;
    public javax.swing.JPanel jpLixo1;
    private javax.swing.JPanel jpStatus1;
    public javax.swing.JLabel lbEncerra;
    public javax.swing.JLabel lbFornecedor;
    public javax.swing.JLabel lbFornecedor1;
    public javax.swing.JTextField tfClientes;
    public javax.swing.JTextField tfTotal;
    private javax.swing.JTabbedPane tpTable;
    // End of variables declaration//GEN-END:variables

    private void mouseEntra(javax.swing.JComponent c) {                                                  
        try{
            c.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            c.setForeground(new java.awt.Color(0, 0, 204));

            c.setBackground(Color.YELLOW);
            c.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        }catch(Exception e ){}
    }
    
    private void mouseSai(javax.swing.JComponent c) {                                                  
        try{
            c.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            c.setForeground(new java.awt.Color(0, 0, 0));

            c.setBackground(Color.WHITE);
            c.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        }catch(Exception e ){}
    }
    
    Venda_New Venda_New_Selecionar;
    private void selecionarClientes() {
      
        Venda_New_Selecionar = this;
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            Clientes_Home Fornecedor_Home = new Clientes_Home( Venda_Home.Home, Venda_New_Selecionar );
            JPanel jp = new JPanel();
            jp.setLayout( new BorderLayout() );
            jp.add      ( Fornecedor_Home, BorderLayout.CENTER  );
            
            Venda_Home.Home.ControleTabs.AddTabSemControleNovo(Venda_Home.tabHome, "Selecionar Cliente", "/utilidades_imagens/icon.png", jp ); 
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "addAbaPesquisa(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start();    
    }
    
    private void selecionarProduto() {                                                  
        Venda_New_Selecionar = this;
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            Produtos_Home Produtos_Home = new Produtos_Home( Venda_Home.Home, Venda_New_Selecionar );
            JPanel jp = new JPanel();
            jp.setLayout( new BorderLayout() );
            jp.add      ( Produtos_Home, BorderLayout.CENTER  );
            
            Venda_Home.Home.ControleTabs.AddTabSemControleNovo(Venda_Home.tabHome, "Selecionar Produto", "/utilidades_imagens/icon.png", jp ); 
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "selecionarProduto(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
    }
    
    public void setarNoJPanelClientesSelecionado( clientes.Clientes Clientes2 ) {                                                  
        try{

            Clientes = Clientes2;
            
            tfClientes.setText(Clientes.getNome() );
            
            btSalvar.setEnabled(true);
            
            //System.out.println( "**********" + Fornecedor4.getNomeourazaosocial());
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelFornecedorSelecionado(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }
    
    public void setarNoJPanelProdutosSelecionado( produtos.Produtos Produtos2 ) {  
        boolean b = false;
        try{
            if ( Tabela_New_Pesquisa.tmPesquisa.getRowCount() > 0 ){ 
                                
                for (int i = 0; i < Tabela_New_Pesquisa.tmPesquisa.getRowCount(); i++){
                    
                    if( Tabela_New_Pesquisa.tbPesquisa.getValueAt( i, 1 ).equals( Produtos2.getCodigo().trim() )  ) {
                        
                        b = false;
                    }
                }
                
                verificarSeProdutoRepete( Produtos2, b );
                
            } else { 
                OperacaoRealizada OPS = new OperacaoRealizada(); OPS.setVisible(true); 
                pegarDadosProduto( Produtos2 ); 
            }
  
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelProdutoSelecionado( produto.Produto Produto2 ), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }
    
    public void verificarSeProdutoRepete( produtos.Produtos Produtos2, boolean b ) {  
        try{
            if ( b == true ){ 
                                
                JOPM JOptionPaneMod = new JOPM( 2, "Tentativa de adicionar Produto, \n"
                                + "O Produto: " + Produtos2.getCodigo() + " - " + Produtos2.getNome()
                                + "\nNão pode ser adicionado, Por que o mesmo já se encontra na"
                                + "\nTabela de destino do Gestor de Compras Atual"    
                                + "\n", "Adicionar Produto" );
                
            } else if ( b == false ){
                
                OperacaoRealizada OPS = new OperacaoRealizada(); OPS.setVisible(true); 
                pegarDadosProduto( Produtos2 ); 
            }
  
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelProdutoSelecionado( produto.Produto Produto2 ), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }
    
    private void pegarDadosProduto( produtos.Produtos Produtos2 ) {  
        try{
            
            vTotal += Produtos2.getCusto();
            tfTotal.setText( String.valueOf( vTotal ) );
            
            Tabela_New_Pesquisa.mostrarLista2( Produtos2 );
            
            btLixo.setEnabled(true);
            
            btSalvar.setEnabled(true);
        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "pegarDadosProduto( produto.Produto Produto2 ), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }

}