/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package assunto_new;

import java.awt.Color;
import assunto.Assunto_Home;
import categorias_new.BookInfoMateria;
import subcategoria_new.BookInfoCategoria;
import utilidades.Alterar_Propriedades;
import utilidades.JFileChooserJM;

/**
 *
 * @author AnaMariana
 */
public class Assunto_New extends javax.swing.JPanel {

    Assunto_Home              Assunto_Home;
    public Assunto_New_Inicio Inicio;
    
    /**
     * Creates new form Cliente
     * @param Assunto_Home2
     */
    public Assunto_New( Assunto_Home Assunto_Home2 ) {
        initComponents();
        
        Assunto_Home = Assunto_Home2;
        
        Inicio = new Assunto_New_Inicio(this); 
        
        jpPgHtml.setVisible( false );
    }
    
    ///////////////////////////////////////////////////////////////////////////
    public assunto.Assunto Assunto;
    public Assunto_New( Assunto_Home Assunto_Home2, assunto.Assunto Assunto2 ) {
        initComponents();
        
        Assunto_Home  = Assunto_Home2;
        
        Assunto = Assunto2;        
        Inicio = new Assunto_New_Inicio( this, Assunto2 );
        
        jpPgHtml.setVisible( true );
    }
    ///////////////////////////////////////////////////////////////////////////
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jp2 = new javax.swing.JPanel();
        cbSubcategoria = new javax.swing.JComboBox();
        lbSubcategoria = new javax.swing.JLabel();
        cbMateria = new javax.swing.JComboBox();
        lbMateria = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jpStatus = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jpPgHtml = new javax.swing.JPanel();
        tfPaHtml = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do assunto");

        cbSubcategoria.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbSubcategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbSubcategoria.setPreferredSize(new java.awt.Dimension(190, 24));
        cbSubcategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbSubcategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbSubcategoriaMouseExited(evt);
            }
        });
        cbSubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubcategoriaActionPerformed(evt);
            }
        });

        lbSubcategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbSubcategoria.setText("Subcategoria");

        cbMateria.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbMateria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbMateria.setPreferredSize(new java.awt.Dimension(190, 24));
        cbMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbMateriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbMateriaMouseExited(evt);
            }
        });
        cbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriaActionPerformed(evt);
            }
        });

        lbMateria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbMateria.setText("Matéria");

        lbCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCategoria.setText("Categoria");

        cbCategoria.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbCategoria.setPreferredSize(new java.awt.Dimension(190, 24));
        cbCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbCategoriaMouseExited(evt);
            }
        });
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbSubcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addComponent(lbSubcategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jp2Layout.createSequentialGroup()
                    .addComponent(lbCategoria)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp2Layout.createSequentialGroup()
                    .addComponent(lbMateria)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tfNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tfNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomeMouseExited(evt);
            }
        });
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Assunto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpStatus.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpStatusLayout = new javax.swing.GroupLayout(jpStatus);
        jpStatus.setLayout(jpStatusLayout);
        jpStatusLayout.setHorizontalGroup(
            jpStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatusLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addContainerGap())
        );

        jpStatusLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAtualizar, btSalvar});

        jpStatusLayout.setVerticalGroup(
            jpStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btAtualizar))
        );

        jpStatusLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAtualizar, btSalvar});

        tfPaHtml.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tfPaHtml.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfPaHtml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfPaHtmlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfPaHtmlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfPaHtmlMousePressed(evt);
            }
        });
        tfPaHtml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPaHtmlKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Página HTML");

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/pesquisar.gif"))); // NOI18N
        btPesquisar.setText("Localizar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPgHtmlLayout = new javax.swing.GroupLayout(jpPgHtml);
        jpPgHtml.setLayout(jpPgHtmlLayout);
        jpPgHtmlLayout.setHorizontalGroup(
            jpPgHtmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPgHtmlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpPgHtmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPgHtmlLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jpPgHtmlLayout.createSequentialGroup()
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPaHtml))))
        );
        jpPgHtmlLayout.setVerticalGroup(
            jpPgHtmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPgHtmlLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPgHtmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(tfPaHtml, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpPgHtml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPgHtml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
       Inicio.salvar( new assunto.Assunto(), false );
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyReleased
        evtBotaoSalvar();
    }//GEN-LAST:event_tfNomeKeyReleased

    private void tfNomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfNome, true );    
    }//GEN-LAST:event_tfNomeMouseEntered

    private void tfNomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfNome, false );                  
    }//GEN-LAST:event_tfNomeMouseExited

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        Inicio.setarCBMateria(false,new assunto.Assunto());
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void cbSubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubcategoriaActionPerformed
        try{
            //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
            BookInfoSubcategoria obj = (BookInfoSubcategoria) cbSubcategoria.getSelectedItem();
            evtBotaoSalvar();
            //System.out.println( "obj.ID "+obj.ID );
        }
        catch( Exception e ){}
    }//GEN-LAST:event_cbSubcategoriaActionPerformed

    private void cbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriaActionPerformed
        try{
            
            if( cbMateria.getItemCount() > 0 ) {
                
                BookInfoMateria obj = (BookInfoMateria) cbMateria.getSelectedItem();
                
                assunto.Assunto Assunto2 = new assunto.Assunto();
                Assunto2.setIdMateria(obj.ID);
                
                Inicio.setarCBCategoria(false, Assunto2 );                
            } else{ Inicio.setarCBCategoria(false, new assunto.Assunto() ); }
            
            if( cbCategoria.getItemCount() > 0 ) {
                //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
                BookInfoCategoria obj = (BookInfoCategoria) cbCategoria.getSelectedItem();
                
                assunto.Assunto Assunto2 = new assunto.Assunto();
                Assunto2.setIdCategoria(obj.ID);
                
                Inicio.setarCBSubcategoria(false, Assunto2 );
                
                evtBotaoSalvar();
                //System.out.println( "obj.ID "+obj.ID );
            } else{ Inicio.setarCBSubcategoria(false, new assunto.Assunto() ); }
        }
        catch( Exception e ){}
    }//GEN-LAST:event_cbMateriaActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        try{
            if( cbCategoria.getItemCount() > 0 ) {
                //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
                BookInfoCategoria obj = (BookInfoCategoria) cbCategoria.getSelectedItem();
                
                assunto.Assunto Assunto2 = new assunto.Assunto();
                Assunto2.setIdCategoria(obj.ID);
                
                Inicio.setarCBSubcategoria(false, Assunto2 );
                
                evtBotaoSalvar();
                //System.out.println( "obj.ID "+obj.ID );
            }
        }
        catch( Exception e ){}
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void tfPaHtmlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPaHtmlMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfPaHtml, true );
    }//GEN-LAST:event_tfPaHtmlMouseEntered

    private void tfPaHtmlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPaHtmlMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfPaHtml, false );
    }//GEN-LAST:event_tfPaHtmlMouseExited

    private void tfPaHtmlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPaHtmlMousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            JFileChooserJM JFileChooserJM = new JFileChooserJM( "  html    -   jmarysystems.blogspot.com.br", new String [] { "HTM" , "HTML" } );
            tfPaHtml.setText( JFileChooserJM.getString( 2 )  );

        } catch( Exception e ){ } } }.start();
    }//GEN-LAST:event_tfPaHtmlMousePressed

    private void tfPaHtmlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPaHtmlKeyReleased
        evtBotaoSalvar();
    }//GEN-LAST:event_tfPaHtmlKeyReleased

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            JFileChooserJM JFileChooserJM = new JFileChooserJM( "  html    -   jmarysystems.blogspot.com.br", new String [] { "HTM" , "HTML" } );
            tfPaHtml.setText( JFileChooserJM.getString( 2 )  );

        } catch( Exception e ){ } } }.start();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void cbMateriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMateriaMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( cbMateria, true );
    }//GEN-LAST:event_cbMateriaMouseEntered

    private void cbMateriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMateriaMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( cbMateria, false );
    }//GEN-LAST:event_cbMateriaMouseExited

    private void cbCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCategoriaMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( cbCategoria, true );
    }//GEN-LAST:event_cbCategoriaMouseEntered

    private void cbCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCategoriaMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( cbCategoria, false );
    }//GEN-LAST:event_cbCategoriaMouseExited

    private void cbSubcategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSubcategoriaMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( cbSubcategoria, true );
    }//GEN-LAST:event_cbSubcategoriaMouseEntered

    private void cbSubcategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSubcategoriaMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( cbSubcategoria, false );
    }//GEN-LAST:event_cbSubcategoriaMouseExited
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btPesquisar;
    public javax.swing.JButton btSalvar;
    public javax.swing.JComboBox cbCategoria;
    public javax.swing.JComboBox cbMateria;
    public javax.swing.JComboBox cbSubcategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jpPgHtml;
    private javax.swing.JPanel jpStatus;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbSubcategoria;
    public javax.swing.JTextField tfNome;
    public javax.swing.JTextField tfPaHtml;
    // End of variables declaration//GEN-END:variables
            
    private void evtBotaoSalvar(){
        
        if( !tfNome.getText().trim().equals( "" ) ){
            
            btSalvar.setEnabled( true );
        }        
        else{
            
            btSalvar.setEnabled( false );
        }
    }
    
}
