/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package utilidades;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileFilter;
import utilidades_imagens.Imagens;

/**
 *
 * @author pc
 */
public class JFileChooserJM extends javax.swing.JPanel {

    /**
     * Creates new form JFileChooserJM
     */
    private String [] strArray;// = new String [] { "HTM" , "HTML" };
    private String    strProp = "  html    -   jmarysystems.blogspot.com.br";
    
    public JFileChooserJM(  String strProp2, String [] strArray2 ) {
        initComponents();
        
        strArray = strArray2;
        strProp  = strProp2;
    }
    
    public String getString( int x ) {                                            
        String retorno = "";
        try{
            javax.swing.JFileChooser jFileChooser = new javax.swing.JFileChooser();

            FileFilter filter = new ExtensionFileFilter ( strProp, strArray ) ;

            jFileChooser.setFileFilter ( filter ) ;

            int status = jFileChooser.showOpenDialog ( this ) ;

            if ( status == javax.swing.JFileChooser.APPROVE_OPTION ) {
                            
                switch( x ){
                    
                    case 1: retorno = jFileChooser.getSelectedFile().getName(); break;
                    case 2: retorno = jFileChooser.getSelectedFile().getCanonicalPath().replace("\\", "/"); break;  
                    case 3: retorno = new File( jFileChooser.getSelectedFile().getPath() ).toURI().toURL().toString(); break;      
                }

            } else if ( status == javax.swing.JFileChooser.CANCEL_OPTION ) { 
                Class<Imagens> clazzHome = Imagens.class;
                JOPM JOptionPaneMod = new JOPM( 1, "Método: getString( int x )\n"
                        + "\nStatus Da Seleção:"
                        + "\nNenhum documento HTML Selecionado\n"
                        + "\nOK Para Prosseguir"
                        ,"Class: " + this.getClass().getName(), 
                        new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
            }
            
        }catch(Exception e){}
        
        return retorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public static void main( String args[] ){
        
        JFileChooserJM JFileChooserJM = new JFileChooserJM( "  html    -   jmarysystems.blogspot.com.br", new String [] { "HTM" , "HTML" } );
        
        System.out.println( JFileChooserJM.getString( 3 ) );
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
