package exercicios_display;

import br.com.jmary.home.Home;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Query;
import utilidades.JOPM;

/**
 *
 * @author AnaMariana
 */
public class Exercicios_Dysplay extends javax.swing.JPanel {
    
    public Home         Home;
    Query               q;
    
    public int          exeAtual;
    public int          exeQtd;
    public String       letraResposta = "";
    
    Exercicios_Display_Inicio Exercicios_Display_Inicio;
    
    private BookInfoExercicios BookInfoExercicios;
    
    public boolean conteudo       = false;
    public String  materiaEx      = "";
    public String  categoriaEx    = "";
    public String  subcategoriaEx = "";
    public String  assuntoEx      = "";
    
    List<Integer> listN = new ArrayList<Integer>();

    /** Creates new form Sombra*/
    public Exercicios_Dysplay(Home Home2, Query q2) {
        initComponents();
        
        Home = Home2;
        q    = q2;
        exeAtual  = 1;
        
        Exercicios_Display_Inicio = new Exercicios_Display_Inicio( this );
        
        Exercicios_Display_Setar_ProcuraBD Exercicios_Display_Setar_ProcuraBD = new Exercicios_Display_Setar_ProcuraBD( q, exeAtual, this );  
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfQtdQuestoes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfAcertos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfErros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btEscolha = new javax.swing.JButton();
        cbEscolhaExe = new javax.swing.JComboBox();
        pnInferior = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btProximo = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btHome = new javax.swing.JButton();
        tfExeResp = new javax.swing.JLabel();
        lbProxAuto = new javax.swing.JLabel();
        rbProxAuto = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        pnResposta = new javax.swing.JPanel();
        rbA = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        rbD = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        btResposta = new javax.swing.JButton();
        rbVerResp = new javax.swing.JRadioButton();
        jpHome = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(683, 298));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(696, 296));

        jPanel1.setPreferredSize(new java.awt.Dimension(679, 296));

        pnSuperior.setBackground(new java.awt.Color(204, 255, 102));
        pnSuperior.setPreferredSize(new java.awt.Dimension(677, 550));
        pnSuperior.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Quant. Questões:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 64, 3, 0);
        pnSuperior.add(jLabel1, gridBagConstraints);

        tfQtdQuestoes.setEditable(false);
        tfQtdQuestoes.setForeground(new java.awt.Color(0, 0, 255));
        tfQtdQuestoes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfQtdQuestoes.setText("0");
        tfQtdQuestoes.setPreferredSize(new java.awt.Dimension(12, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 3, 0);
        pnSuperior.add(tfQtdQuestoes, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Acertos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 3, 0);
        pnSuperior.add(jLabel2, gridBagConstraints);

        tfAcertos.setEditable(false);
        tfAcertos.setForeground(new java.awt.Color(0, 0, 255));
        tfAcertos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAcertos.setText("0");
        tfAcertos.setPreferredSize(new java.awt.Dimension(12, 18));
        tfAcertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAcertosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 3, 0);
        pnSuperior.add(tfAcertos, gridBagConstraints);

        jLabel3.setText("Erros:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 3, 0);
        pnSuperior.add(jLabel3, gridBagConstraints);

        tfErros.setEditable(false);
        tfErros.setForeground(new java.awt.Color(0, 0, 255));
        tfErros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfErros.setText("0");
        tfErros.setPreferredSize(new java.awt.Dimension(12, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 3, 0);
        pnSuperior.add(tfErros, gridBagConstraints);

        jLabel4.setText("Ir Questão:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 3, 0);
        pnSuperior.add(jLabel4, gridBagConstraints);

        btEscolha.setText("OK");
        btEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscolhaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 3, 64);
        pnSuperior.add(btEscolha, gridBagConstraints);

        cbEscolhaExe.setEditable(true);
        cbEscolhaExe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Digite", "100000", "2", "3" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 3, 0);
        pnSuperior.add(cbEscolhaExe, gridBagConstraints);

        pnInferior.setPreferredSize(new java.awt.Dimension(677, 71));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(675, 38));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercicios_display_imagens/botão_Próximo.png"))); // NOI18N
        btProximo.setBorder(null);
        btProximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btProximoMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -27;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 35, 0, 0);
        jPanel2.add(btProximo, gridBagConstraints);

        btAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercicios_display_imagens/botão_Anterior.png"))); // NOI18N
        btAnterior.setBorder(null);
        btAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAnteriorMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -28;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel2.add(btAnterior, gridBagConstraints);

        btHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercicios_display_imagens/botão_Home.png"))); // NOI18N
        btHome.setBorder(null);
        btHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btHomeMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -3;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 0, 0);
        jPanel2.add(btHome, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 0);
        jPanel4.add(jPanel2, gridBagConstraints);

        tfExeResp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfExeResp.setForeground(new java.awt.Color(255, 255, 255));
        tfExeResp.setText("EXERCÍCIO JÁ RESOLVIDO!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 20, 0, 0);
        jPanel4.add(tfExeResp, gridBagConstraints);

        lbProxAuto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbProxAuto.setText("Próximo Automático");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 122, 0, 0);
        jPanel4.add(lbProxAuto, gridBagConstraints);

        rbProxAuto.setBackground(new java.awt.Color(255, 255, 255));
        rbProxAuto.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 154, 0, 0);
        jPanel4.add(rbProxAuto, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(204, 255, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(675, 65));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        pnResposta.setBackground(new java.awt.Color(255, 255, 255));
        pnResposta.setLayout(new java.awt.GridBagLayout());

        rbA.setText("A");
        rbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        pnResposta.add(rbA, gridBagConstraints);

        rbB.setText("B");
        rbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        pnResposta.add(rbB, gridBagConstraints);

        rbD.setText("D");
        rbD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        pnResposta.add(rbD, gridBagConstraints);

        rbC.setText("C");
        rbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        pnResposta.add(rbC, gridBagConstraints);

        btResposta.setText("Responder");
        btResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRespostaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        pnResposta.add(btResposta, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 103, 0, 125);
        jPanel5.add(pnResposta, gridBagConstraints);

        rbVerResp.setBackground(new java.awt.Color(204, 255, 102));
        rbVerResp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        rbVerResp.setSelected(true);
        rbVerResp.setText("Ver Respostas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel5.add(rbVerResp, gridBagConstraints);

        javax.swing.GroupLayout pnInferiorLayout = new javax.swing.GroupLayout(pnInferior);
        pnInferior.setLayout(pnInferiorLayout);
        pnInferiorLayout.setHorizontalGroup(
            pnInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        pnInferiorLayout.setVerticalGroup(
            pnInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInferiorLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jpHomeLayout = new javax.swing.GroupLayout(jpHome);
        jpHome.setLayout(jpHomeLayout);
        jpHomeLayout.setHorizontalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpHomeLayout.setVerticalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnInferior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addComponent(pnSuperior, 0, 671, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jpHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfAcertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAcertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAcertosActionPerformed

    public void próximoExe(){

    }
    private void rbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAActionPerformed
        //rbA.setSelected(false);
        rbB.setSelected(false);
        rbC.setSelected(false);
        rbD.setSelected(false);
        letraResposta = "A";
    }//GEN-LAST:event_rbAActionPerformed

    private void rbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBActionPerformed
        rbA.setSelected(false);
        //rbB.setSelected(false);
        rbC.setSelected(false);
        rbD.setSelected(false);
        letraResposta = "B";
    }//GEN-LAST:event_rbBActionPerformed

    private void rbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCActionPerformed
        rbA.setSelected(false);
        rbB.setSelected(false);
        //rbC.setSelected(false);
        rbD.setSelected(false);
        letraResposta = "C";
    }//GEN-LAST:event_rbCActionPerformed

    private void rbDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDActionPerformed
        rbA.setSelected(false);
        rbB.setSelected(false);
        rbC.setSelected(false);
        //rbD.setSelected(false);
        letraResposta = "D";
    }//GEN-LAST:event_rbDActionPerformed

    private void btRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRespostaActionPerformed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
                
             if( getBookInfoExercicios().RESPOSTACERTA.equals( letraResposta ) ){
                 int n = Integer.parseInt( tfAcertos.getText().trim() );
                 n+=1;
                 tfAcertos.setText( String.valueOf( n ) );
                 evtRbs();
                 if( rbProxAuto.isSelected() ){
                     addAListResolvidos( BookInfoExercicios.ID );
                     proximoExercicio();
                 }
             }
             else{ //tfErros
                 int n = Integer.parseInt( tfErros.getText().trim() );
                 n+=1;
                 tfErros.setText( String.valueOf( n ) );
                 evtRbs();
                 if( rbProxAuto.isSelected() ){
                     addAListResolvidos( BookInfoExercicios.ID );
                     proximoExercicio();
                 }
             }
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "btRespostaActionPerformed, \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start();  
       
    }//GEN-LAST:event_btRespostaActionPerformed

    private void btEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscolhaActionPerformed
        //String op = cbtipoP.getSelectedItem().toString().trim();
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            int n = Integer.parseInt( cbEscolhaExe.getSelectedItem().toString().trim() );
            
            if( n  >= 1 ){
                exeAtual = n - 1; 
                proximoExercicio();
            }
            else{
                anteriorExercicio();
            }
        } catch( Exception e ){ 
            
            anteriorExercicio();
        } } }.start();  
    }//GEN-LAST:event_btEscolhaActionPerformed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered

    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited

    }//GEN-LAST:event_jPanel4MouseExited

    private void btProximoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximoMousePressed
        proximoExercicio();        
    }//GEN-LAST:event_btProximoMousePressed

    private void btAnteriorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnteriorMousePressed
        anteriorExercicio(); 
    }//GEN-LAST:event_btAnteriorMousePressed

    private void btHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHomeMousePressed
        exeAtual=1; //exeQtd
        Exercicios_Display_Setar_ProcuraBD Exercicios_Display_Setar_ProcuraBD = new Exercicios_Display_Setar_ProcuraBD( q, exeAtual, this );
    }//GEN-LAST:event_btHomeMousePressed
   
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btEscolha;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btResposta;
    public javax.swing.JComboBox cbEscolhaExe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel jpHome;
    private javax.swing.JLabel lbProxAuto;
    private javax.swing.JPanel pnInferior;
    private javax.swing.JPanel pnResposta;
    private javax.swing.JPanel pnSuperior;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbD;
    public javax.swing.JRadioButton rbProxAuto;
    public javax.swing.JRadioButton rbVerResp;
    public javax.swing.JTextField tfAcertos;
    public javax.swing.JTextField tfErros;
    public javax.swing.JLabel tfExeResp;
    public javax.swing.JTextField tfQtdQuestoes;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the BookInfoExercicios
     */
    public BookInfoExercicios getBookInfoExercicios() {
        return BookInfoExercicios;
    }

    /**
     * @param BookInfoExercicios the BookInfoExercicios to set
     */
    public void setBookInfoExercicios(BookInfoExercicios BookInfoExercicios) {
        this.BookInfoExercicios = BookInfoExercicios;
    }
    
    private void evtRbs(){
                        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
                
            letraResposta = "";
            rbA.setSelected(false);
            rbB.setSelected(false);
            rbC.setSelected(false);
            rbD.setSelected(false);
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "evtRbs, \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start();         
    }
    
    private void proximoExercicio() {                                       
        exeAtual+=1; 
        if( exeAtual  > exeQtd ){
            exeAtual = 1;
        }
        Exercicios_Display_Setar_ProcuraBD Exercicios_Display_Setar_ProcuraBD = new Exercicios_Display_Setar_ProcuraBD( q, exeAtual, this );        
    }
    
    private void anteriorExercicio() {                                      
        exeAtual-=1;
        if( exeAtual  < 1 ){
            exeAtual = 1;
        }
        Exercicios_Display_Setar_ProcuraBD Exercicios_Display_Setar_ProcuraBD = new Exercicios_Display_Setar_ProcuraBD( q, exeAtual, this );  
    }
    
    private void addAListResolvidos( int n ) {   
        
        if( !listN.isEmpty() ){
            for (int i = 0; i < listN.size(); i++){
                if( n == listN.get(i) ){
                    System.out.println( " break " );
                    break;
                }
                else{
                    int ci = i + 1;
                    int cl = listN.size();
                    if( ci == cl ) {  
                        System.out.println( " N " + n );
                        listN.add(n);
                    }
                }
            }
        }
        else{
            listN.add(n);
        }
        
    }
      
}
