/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import utilidades.CentralizarJanela;
import controleThread.ControleThread_Login;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import login_control.Login_Bean;
import login_control.Login_Control_Listar;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import utilidades.DB_Conexao;
import utilidades.JOPM;

/**
 *
 * @author AnaMariana
 */
public class LoginDerby extends javax.swing.JFrame {

    /**
     * Creates new form SetorInicial
     */
    public LoginDerby() {
        initComponents();  
        pfsenha.setEchoChar('*');  
        
        inicio();
    }
    
    LoginDerby_Inicio t1;
    private void inicio() {        
        
        String endereco_db     = System.getProperty("user.home") + System.getProperty("file.separator") + "JMarySystems";   
        t1 = new LoginDerby_Inicio( this, endereco_db );   
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );           
                                                     
            t1.setName("LoginDerby_Inicio");         
            t1.start();  
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "inicio(), \n"
                + e.getMessage() + "\n", "LoginDerby " ); } } }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbConfigurarConexao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btConectar = new javax.swing.JButton();
        btOcultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tfLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pfsenha = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        tfStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:JMARY..SYSTEMS:.");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_imagens/login.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TELA DE ACESSO");

        lbConfigurarConexao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbConfigurarConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_imagens/ip.png"))); // NOI18N
        lbConfigurarConexao.setToolTipText("Alterar configurações do servidor");
        lbConfigurarConexao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbConfigurarConexaoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbConfigurarConexao)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lbConfigurarConexao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("INFORME O NOME DE USUÁRIO E SENHA");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btConectar.setText("Conectar");
        btConectar.setEnabled(false);
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });

        btOcultar.setText("Cancelar");
        btOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOcultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btOcultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConectar)
                    .addComponent(btOcultar)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tfLogin.setBackground(new java.awt.Color(240, 240, 240));
        tfLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoginActionPerformed(evt);
            }
        });
        tfLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLoginKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Usuario:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Senha:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_imagens/logocangaco.png"))); // NOI18N

        pfsenha.setBackground(new java.awt.Color(240, 240, 240));
        pfsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfsenhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pfsenha)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pfsenha, tfLogin});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, pfsenha, tfLogin});

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tfStatus.setEditable(false);
        tfStatus.setBackground(new java.awt.Color(255, 255, 255));
        tfStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfStatus.setForeground(new java.awt.Color(0, 51, 255));
        tfStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStatus.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfStatus, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectarActionPerformed
        conectar();
    }//GEN-LAST:event_btConectarActionPerformed

    private void conectar() {                                           
        if( !tfLogin.getText().trim().equals("") ) {
            
            ControleThread_Login t1 = new ControleThread_Login( this );        
            t1.setName("Controle Thread Login");         
            t1.start();  
            
        }                          
        else {
            JOPM JOptionPaneMod = new JOPM( 2, "conectar(), \n" + "\n", "Informe o nome do usuário" );
        }
    }
    
    private void btOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOcultarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btOcultarActionPerformed

    private void tfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoginActionPerformed

    private void lbConfigurarConexaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbConfigurarConexaoMousePressed
        configurarConexao();      
    }//GEN-LAST:event_lbConfigurarConexaoMousePressed

    JFrame frame;
    DB_Conexao DB_Conexao;
    public void configurarConexao() {                                                 
        thisSetVisible(false);
        
        DB_Conexao = new DB_Conexao(this);
        
        frame = new JFrame( ".:JMary_Systems:.", null );
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //JFrame.DO_NOTHING_ON_CLOSE //Cancela o Botão fechar         
        frame.setContentPane( DB_Conexao );        
        frame.setResizable(false);
        
        frame.addWindowListener(new WindowAdapter() {  
            public void windowClosing(WindowEvent evt) {  
                   if (JOptionPane.showConfirmDialog(null,"Deseja salvar")==JOptionPane.OK_OPTION){  
                        btConectar.setEnabled( true );
                        thisSetVisible(true);
                        DB_Conexao.criarConfiguracoesDB();
                   }  
                   else{
                       btConectar.setEnabled( true );
                       thisSetVisible(true);
                   }
                }  
        }); 
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            frame.setIconImage(null);
        
            try{ frame.setUndecorated(true);                                    } catch( Exception e ){}
            try{ frame.getRootPane().setWindowDecorationStyle(JRootPane.FRAME); } catch( Exception e ){}
            //try{ frame.setExtendedState(JFrame.MAXIMIZED_BOTH);                 } catch( Exception e ){}  
       
            CentralizarJanela Centralizar = new CentralizarJanela( frame );
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "lbConfigurarConexao(), \n"
                + e.getMessage() + "\n", "LoginDerby" ); } } }.start();        
    }
    
    public void fecharFrameConf(){
        frame.dispose();
    }
    public void thisSetVisible(boolean b){
        this.setVisible(b);
    }
    
    private void pfsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfsenhaKeyPressed
        if( evt.getKeyCode() == KeyEvent.VK_ENTER )  {  
             
            conectar();
            
        }
    }//GEN-LAST:event_pfsenhaKeyPressed

    private void tfLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLoginKeyPressed
        if( evt.getKeyCode() == KeyEvent.VK_ENTER )  {  
             
            conectar();
            
        }
    }//GEN-LAST:event_tfLoginKeyPressed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDerby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDerby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDerby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDerby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDerby().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btConectar;
    private javax.swing.JButton btOcultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbConfigurarConexao;
    private javax.swing.JPasswordField pfsenha;
    private javax.swing.JTextField tfLogin;
    public javax.swing.JTextField tfStatus;
    // End of variables declaration//GEN-END:variables
    //TestarConexaoComOBanco
    
    public void verificarLogin( String ip_do_servidor ){  //System.out.println( login );
        
        String login = tfLogin.getText().trim(); 
        char[] senha = pfsenha.getPassword();
        
        Login_Control_Listar Control = new Login_Control_Listar();
        List<Login_Bean> List_Bean_Login = Control.listar( "%"+""+"%" );
                
        mostrarLista( List_Bean_Login, login, senha, ip_do_servidor );
    }
    
    protected void mostrarLista( List<Login_Bean> List_Bean_Login, String login, char[] senha, String ip_do_servidor ){
                                                 
        for (int i = 0; i < List_Bean_Login.size(); i++){ 
            
            //System.out.println( i+" - "+List_Bean_Login.get(i).getLOGIN() );
                                                 
            if( List_Bean_Login.get(i).getLOGIN().equals( login ) ) {
                                                 
                if( passwordCorreto( senha, List_Bean_Login.get(i).getSENHA() ) ) { 
                    
                    System.out.println( "Usuário encontrado e senha confere" );
                    Home_ControleThread C = new Home_ControleThread( List_Bean_Login.get(i).getID() );
                    C.setName("Thread1");          
                    C.start(); 
                    
                    this.dispose();
                    break;
                }
                else {
                    
                    JOptionPane.showMessageDialog( null, "Usuário: " + login  + "\nSenha incorreta" );
                    break; 
                }
            }
            
            if( i == List_Bean_Login.size() - 1 ){ JOptionPane.showMessageDialog( null, "Usuário não cadastrado!" ); }                       
        }
    }
    
    private static boolean passwordCorreto( char[] senhaDigitada, String senhaDoDB ) {
        boolean isCorrect = true;
        char[] senhaCorreta = senhaDoDB.toCharArray();   
 
        if (senhaDigitada.length != senhaCorreta.length) {
            isCorrect = false;
        } else {
            isCorrect = Arrays.equals (senhaDigitada, senhaCorreta);
        }
 
        //Zero out the password.
        Arrays.fill(senhaCorreta,'0');
 
        return isCorrect;
    }
    
    
}
