/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicios_new;

import utilidades.ExtensionFileFilter;
import assunto_new.BookInfoSubcategoria;
import categorias_new.BookInfoMateria;
import exercicios.Exercicios;
import exercicios.Exercicios_Home;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import subcategoria_new.BookInfoCategoria;
import utilidades.JFileChooserJM;

/**
 *
 * @author AnaMariana
 */
public class Exercicios_New extends javax.swing.JPanel {

    Exercicios_Home Exercicios_Home;
    public Exercicios_New_Inicio Exercicios_New_Inicio;
    public Metodos Metodos;
    
    /**
     * Creates new form Cliente
     * @param Exercicios_Home2
     */
    public Exercicios_New( Exercicios_Home Exercicios_Home2 ) {
        initComponents();
        
        Exercicios_Home = Exercicios_Home2;
        
        Exercicios_New_Inicio = new Exercicios_New_Inicio( this );
        
        Metodos = new Metodos( this );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpStatus = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbMateria = new javax.swing.JComboBox();
        cbCategoria = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbSubcategoria = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbAssunto = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        scPergunta = new javax.swing.JScrollPane();
        jpPergunta = new javax.swing.JPanel();
        tfEnderecoPergunta = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        rbA = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        rbD = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        scPergunta1 = new javax.swing.JScrollPane();
        jpPergunta1 = new javax.swing.JPanel();
        tfEnderecoResposta = new javax.swing.JTextField();
        btPesquisar1 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Exercício");

        jpStatus.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);

        javax.swing.GroupLayout jpStatusLayout = new javax.swing.GroupLayout(jpStatus);
        jpStatus.setLayout(jpStatusLayout);
        jpStatusLayout.setHorizontalGroup(
            jpStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addContainerGap())
        );
        jpStatusLayout.setVerticalGroup(
            jpStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatusLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jpStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar))
                .addContainerGap())
        );

        jLabel2.setText("Matéria");

        cbMateria.setPreferredSize(new java.awt.Dimension(190, 24));
        cbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriaActionPerformed(evt);
            }
        });

        cbCategoria.setPreferredSize(new java.awt.Dimension(190, 24));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria");

        cbSubcategoria.setPreferredSize(new java.awt.Dimension(190, 24));
        cbSubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubcategoriaActionPerformed(evt);
            }
        });

        jLabel4.setText("Subcategoria");

        cbAssunto.setPreferredSize(new java.awt.Dimension(190, 24));
        cbAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAssuntoActionPerformed(evt);
            }
        });

        jLabel5.setText("Assunto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSubcategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        scPergunta.setBorder(null);

        jpPergunta.setPreferredSize(new java.awt.Dimension(100, 100));

        tfEnderecoPergunta.setEditable(false);
        tfEnderecoPergunta.setPreferredSize(new java.awt.Dimension(59, 24));
        tfEnderecoPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEnderecoPerguntaActionPerformed(evt);
            }
        });

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/pesquisar.gif"))); // NOI18N
        btPesquisar.setText("Localizar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane9.setViewportView(jTextArea1);

        javax.swing.GroupLayout jpPerguntaLayout = new javax.swing.GroupLayout(jpPergunta);
        jpPergunta.setLayout(jpPerguntaLayout);
        jpPerguntaLayout.setHorizontalGroup(
            jpPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPerguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPerguntaLayout.createSequentialGroup()
                        .addComponent(btPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEnderecoPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
        jpPerguntaLayout.setVerticalGroup(
            jpPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPerguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEnderecoPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpPerguntaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btPesquisar, tfEnderecoPergunta});

        scPergunta.setViewportView(jpPergunta);

        jTabbedPane1.addTab("Pergunta", scPergunta);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        rbA.setText("A");
        rbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAActionPerformed(evt);
            }
        });

        rbB.setText("B");
        rbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBActionPerformed(evt);
            }
        });

        rbC.setText("C");
        rbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCActionPerformed(evt);
            }
        });

        rbD.setText("D");
        rbD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDActionPerformed(evt);
            }
        });

        jLabel6.setText("Resposta correta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbA)
                        .addGap(18, 18, 18)
                        .addComponent(rbB)
                        .addGap(18, 18, 18)
                        .addComponent(rbC)
                        .addGap(18, 18, 18)
                        .addComponent(rbD)))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbA)
                    .addComponent(rbB)
                    .addComponent(rbC)
                    .addComponent(rbD))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Resposta Correta", jPanel2);

        scPergunta1.setBorder(null);

        jpPergunta1.setPreferredSize(new java.awt.Dimension(100, 100));

        tfEnderecoResposta.setEditable(false);
        tfEnderecoResposta.setPreferredSize(new java.awt.Dimension(59, 24));
        tfEnderecoResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEnderecoRespostaActionPerformed(evt);
            }
        });

        btPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/pesquisar.gif"))); // NOI18N
        btPesquisar1.setText("Localizar");
        btPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar1ActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane10.setViewportView(jTextArea2);

        javax.swing.GroupLayout jpPergunta1Layout = new javax.swing.GroupLayout(jpPergunta1);
        jpPergunta1.setLayout(jpPergunta1Layout);
        jpPergunta1Layout.setHorizontalGroup(
            jpPergunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPergunta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPergunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPergunta1Layout.createSequentialGroup()
                        .addComponent(btPesquisar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEnderecoResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane10))
                .addContainerGap())
        );
        jpPergunta1Layout.setVerticalGroup(
            jpPergunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPergunta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPergunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEnderecoResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        scPergunta1.setViewportView(jpPergunta1);

        jTabbedPane1.addTab("Resposta", scPergunta1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Exercicios_New_Inicio.salvar( new Exercicios() );
    }//GEN-LAST:event_btSalvarActionPerformed

    private void cbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriaActionPerformed
        evtcbMateria();
        evtcbCategoria();
        evtcbSubcategoria();
        evtCombo();
    }//GEN-LAST:event_cbMateriaActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        evtcbCategoria();
        evtcbSubcategoria();
        evtCombo();
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void cbSubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubcategoriaActionPerformed
        evtcbSubcategoria();
        evtCombo();
    }//GEN-LAST:event_cbSubcategoriaActionPerformed

    private void cbAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAssuntoActionPerformed
        try{               
            if( cbAssunto.getItemCount() > 0 ) {
                //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
                BookInfoAssunto obj = (BookInfoAssunto) cbAssunto.getSelectedItem();
                
                cbAssunto.setToolTipText(obj.ASSUNTO);
                
                evtBotaoSalvar();
            } else{ 
                cbAssunto.setToolTipText("");}
            evtCombo();
        }
        catch( Exception e ){}
    }//GEN-LAST:event_cbAssuntoActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        try{
            JFileChooserJM JFCJM = new JFileChooserJM( "  html    -   jmarysystems.blogspot.com.br" , new String [] { "HTM" , "HTML" } );
            String str = JFCJM.getString( 1 );
            tfEnderecoPergunta.setText( str  );
            evtBotaoSalvar();
        }catch(Exception e){}
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void tfEnderecoPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEnderecoPerguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEnderecoPerguntaActionPerformed

    private void tfEnderecoRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEnderecoRespostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEnderecoRespostaActionPerformed

    private void btPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar1ActionPerformed
        /*SelecionarImgProd.setFileSelectionMode ( JFileChooser.DIRECTORIES_ONLY ) ;
        SelecionarImgProd.showOpenDialog ( this ) ; */
        /*       Usando A Classe: ExtensionFileFilter.java        */
        JFileChooser jFileChooser = new JFileChooser();

        FileFilter filter1 = new ExtensionFileFilter ( "  html    -   jmarysystems.blogspot.com.br" , new String [] { "HTM" , "HTML" }) ;

        jFileChooser.setFileFilter ( filter1 ) ;

        int status = jFileChooser.showOpenDialog ( this ) ;

        if ( status == JFileChooser.APPROVE_OPTION ) {
            File selectedFile = jFileChooser.getSelectedFile () ;

            try{
                tfEnderecoResposta.setText( selectedFile.getName()  );
                evtBotaoSalvar();
                //Icone  = SelecionarImgProd.getSelectedFile ().getCanonicalPath().replace("\\", "/");  
                    //labelFoto.setIcon(new ImageIcon(Icone));
                }catch(Exception e){}
                /*
                String EndereçoImagem  = ( selectedFile.getParent ());
                String NomeImagem = ( selectedFile.getName ());

                JOptionPane.showMessageDialog(this,"Nome: "+NomeImagem
                    +"\nEndereço: "+EndereçoImagem
                    +"\nIcone: "+Icone
                ); */

            } else if ( status == JFileChooser.CANCEL_OPTION ) {
                JOptionPane.showMessageDialog(this,"Status Da Seleção:"
                    +"\nNenhum documento HTML Selecionado,"
                    + "\nHTM ou HTML"
                    ,"SELECIONE UM ARQUIVO:",JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btPesquisar1ActionPerformed

    private void rbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAActionPerformed
        //rbA.setSelected(false);
        rbB.setSelected(false);
        rbC.setSelected(false);
        rbD.setSelected(false);
        evtBotaoSalvar();
    }//GEN-LAST:event_rbAActionPerformed

    private void rbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBActionPerformed
        rbA.setSelected(false);
        //rbB.setSelected(false);
        rbC.setSelected(false);
        rbD.setSelected(false);
        evtBotaoSalvar();
    }//GEN-LAST:event_rbBActionPerformed

    private void rbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCActionPerformed
        rbA.setSelected(false);
        rbB.setSelected(false);
        //rbC.setSelected(false);
        rbD.setSelected(false);
        evtBotaoSalvar();
    }//GEN-LAST:event_rbCActionPerformed

    private void rbDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDActionPerformed
        rbA.setSelected(false);
        rbB.setSelected(false);
        rbC.setSelected(false);
        //rbD.setSelected(false);
        evtBotaoSalvar();
    }//GEN-LAST:event_rbDActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btPesquisar;
    public javax.swing.JButton btPesquisar1;
    public javax.swing.JButton btSalvar;
    public javax.swing.JComboBox cbAssunto;
    public javax.swing.JComboBox cbCategoria;
    public javax.swing.JComboBox cbMateria;
    public javax.swing.JComboBox cbSubcategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel jpPergunta;
    private javax.swing.JPanel jpPergunta1;
    private javax.swing.JPanel jpStatus;
    public javax.swing.JRadioButton rbA;
    public javax.swing.JRadioButton rbB;
    public javax.swing.JRadioButton rbC;
    public javax.swing.JRadioButton rbD;
    private javax.swing.JScrollPane scPergunta;
    private javax.swing.JScrollPane scPergunta1;
    public javax.swing.JTextField tfEnderecoPergunta;
    public javax.swing.JTextField tfEnderecoResposta;
    // End of variables declaration//GEN-END:variables
    
    private void evtcbMateria() {                                          
        try{            
            if( cbMateria.getItemCount() > 0 ) {
                
                BookInfoMateria obj = (BookInfoMateria) cbMateria.getSelectedItem();
                
                cbMateria.setToolTipText(obj.MATERIA);
                
                exercicios.Exercicios Exercicios2 = new exercicios.Exercicios();
                Exercicios2.setIdMateria(obj.ID);
                                                
                Exercicios_New_Inicio.setarCBCategoria(false, Exercicios2 );                
            } else{ 
                cbMateria.setToolTipText("");
                Exercicios_New_Inicio.setarCBCategoria(false, new exercicios.Exercicios() ); }
        }
        catch( Exception e ){}
    }
    
    private void evtcbCategoria() {                                          
        try{               
            if( cbCategoria.getItemCount() > 0 ) {
                //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
                BookInfoCategoria obj = (BookInfoCategoria) cbCategoria.getSelectedItem();
                
                cbCategoria.setToolTipText(obj.CATEGORIA);
                
                exercicios.Exercicios Exercicios2 = new exercicios.Exercicios();
                Exercicios2.setIdCategoria(obj.ID);
                
                Exercicios_New_Inicio.setarCBSubcategoria(false, Exercicios2 );
                
                evtBotaoSalvar();
                //System.out.println( "obj.ID "+obj.ID );
            } else{
                cbCategoria.setToolTipText("");
                Exercicios_New_Inicio.setarCBSubcategoria(false, new exercicios.Exercicios() ); }
        }
        catch( Exception e ){}
    }
    
    private void evtcbSubcategoria() {                                          
        try{               
            if( cbSubcategoria.getItemCount() > 0 ) {
                //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
                BookInfoSubcategoria obj = (BookInfoSubcategoria) cbSubcategoria.getSelectedItem();
                
                cbSubcategoria.setToolTipText(obj.SUBCATEGORIA);
                
                exercicios.Exercicios Exercicios2 = new exercicios.Exercicios();
                Exercicios2.setIdSubcategoria(obj.ID);
                
                Exercicios_New_Inicio.setarCBAssunto(false, Exercicios2 );
                
                evtBotaoSalvar();
                //System.out.println( "obj.ID "+obj.ID );
            } else{ 
                cbSubcategoria.setToolTipText("");
                Exercicios_New_Inicio.setarCBAssunto(false, new exercicios.Exercicios() ); }
        }
        catch( Exception e ){}
    }
    
    private void evtBotaoSalvar(){ 
        EvtBotaoSalvar_Thread t1 = new EvtBotaoSalvar_Thread( this );         
        t1.setName("EvtBotaoSalvar_Thread");           
        t1.start();  
    }
    
    private void evtCombo(){
        tfEnderecoPergunta.setText("");
        tfEnderecoResposta.setText("");
        rbA.setSelected(false);
        rbB.setSelected(false);
        rbC.setSelected(false);
        rbD.setSelected(false);
        btSalvar.setEnabled( false );
    }
    
}
