/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_designer;

import br.com.jmary.home.Home;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicSplitPaneUI;

/**
 *
 * @author Ana
 */
public class BarraJEditorPane extends javax.swing.JPanel {

    /**
     * Creates new form BarraJEditorPane
     */
    public BarraJEditorPane( Home Home2, JPHtmlPrincipal JPHtmlPrincipal2 ) {
        initComponents();
        
        Home = Home2; 
        JPHtmlPrincipal = JPHtmlPrincipal2;
    }
    
    Home Home; 
    JPHtmlPrincipal JPHtmlPrincipal; 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btPosTrees = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        btPosTrees.setText("<<");
        btPosTrees.setToolTipText("Contrair Descontrair JTREE");
        btPosTrees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPosTrees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPosTreesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btPosTrees)
                .addContainerGap(367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btPosTrees)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btPosTreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPosTreesActionPerformed
        String tx = btPosTrees.getText().trim();
        switch (tx) {
            case "<<":
                splitPane( 0 );
                btPosTrees.setText(">>");
                break;
            case ">>":
                splitPane( 1 );
                btPosTrees.setText("<<");
                break;
        }
    }//GEN-LAST:event_btPosTreesActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPosTrees;
    // End of variables declaration//GEN-END:variables

    private void splitPane( int zeroOuUm ){
        //spPrincipal.setDividerLocation(80);
        try{
            
            BasicSplitPaneUI ui = (BasicSplitPaneUI)JPHtmlPrincipal.jSplitPaneHtmlPrincipal.getUI();
            JButton oneClick = (JButton)ui.getDivider().getComponent( zeroOuUm );
            oneClick.doClick();
        
        } catch( Exception e ){
            JOptionPane.showMessageDialog(null, "BarraJEditorPane - Método: splitPane\n" + e.getMessage().toString());
        }
    }
    
}
