/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema_submenus;

import clientes.Clientes_Home;
import produtos.Produtos_Home;
import sistema.Sistema_Home;
import venda.Venda_Home;

/**
 *
 * @author ana
 */
public class Submenu1 extends javax.swing.JPanel {

    Sistema_Home Sistema_Home;
        
    public Submenu1( Sistema_Home Sistema_Home2 ) {
        Sistema_Home = Sistema_Home2;
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btExercicios3 = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        btExercicios6 = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        btExercicios = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btExercicios4 = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jToolBar2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setPreferredSize(new java.awt.Dimension(658, 71));

        jSeparator7.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator7);

        btExercicios3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_imagens/home.png"))); // NOI18N
        btExercicios3.setText("Home");
        btExercicios3.setFocusable(false);
        btExercicios3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExercicios3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExercicios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExercicios3MousePressed(evt);
            }
        });
        jToolBar2.add(btExercicios3);

        jSeparator13.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator13);

        btExercicios6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/cliente.png"))); // NOI18N
        btExercicios6.setText("Clientes");
        btExercicios6.setFocusable(false);
        btExercicios6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExercicios6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExercicios6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExercicios6MousePressed(evt);
            }
        });
        jToolBar2.add(btExercicios6);

        jSeparator16.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator16);

        btExercicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/produtos.png"))); // NOI18N
        btExercicios.setText("Produtos");
        btExercicios.setFocusable(false);
        btExercicios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExercicios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExerciciosMousePressed(evt);
            }
        });
        jToolBar2.add(btExercicios);

        jSeparator10.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator10);

        btExercicios4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/novavenda.png"))); // NOI18N
        btExercicios4.setText("Nova Venda");
        btExercicios4.setFocusable(false);
        btExercicios4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExercicios4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExercicios4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExercicios4MousePressed(evt);
            }
        });
        jToolBar2.add(btExercicios4);

        jSeparator14.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator14);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btExerciciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExerciciosMousePressed
        if( btExercicios.isEnabled() == true ){
            try{                
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("Produtos", "/sistema_imagens/livroTp.gif", new Produtos_Home( Sistema_Home.Home ) );                     
            } catch( Exception e ){}             
        }         
    }//GEN-LAST:event_btExerciciosMousePressed

    private void btExercicios3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExercicios3MousePressed
        Sistema_Home.Home.tabHome.setSelectedIndex( 0 );
    }//GEN-LAST:event_btExercicios3MousePressed

    private void btExercicios4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExercicios4MousePressed
        if( btExercicios4.isEnabled() == true ){
            try{                
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("Nova Venda", "/sistema_imagens/livroTp.gif", new Venda_Home( Sistema_Home.Home ) );                     
            } catch( Exception e ){}             
        }
    }//GEN-LAST:event_btExercicios4MousePressed

    private void btExercicios6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExercicios6MousePressed
        if( btExercicios6.isEnabled() == true ){
            try{                
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("Clientes", "/sistema_imagens/livroTp.gif", new Clientes_Home( Sistema_Home.Home ) );                     
            } catch( Exception e ){}             
        }  
    }//GEN-LAST:event_btExercicios6MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExercicios;
    private javax.swing.JButton btExercicios3;
    private javax.swing.JButton btExercicios4;
    private javax.swing.JButton btExercicios6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
