/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package subcategoria_search;

import categorias_new.BookInfoMateria;
import home_usuario_logado.Bean_Usuario_Logado;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.List;
import javax.persistence.Query;
import jpa.JPAUtil;
import subcategoria.Subcategorias_Home;
import subcategoria.Subcategoria;
import subcategoria_new.BookInfoCategoria;
import subcategoria_new.Subcategorias_New;
import utilidades.DB;
import utilidades.JOPM;

/**
 *
 * @author AnaMariana
 */
public class Menu_Pesquisa_Subcategorias extends javax.swing.JPanel {

    Subcategorias_Home                      Subcategorias_Home;
    public  int                             IDSELECIONADA; 
    public Tabela_Pesquisa_BD_Subcategorias Tabela_Pesquisa_BD_Subcategorias;
     
    /**
     * Creates new form Cliente
     * @param Materias_Home2
     */
    public Menu_Pesquisa_Subcategorias( Subcategorias_Home Subcategorias_Home2 ) {
        initComponents();
        
        Subcategorias_Home = Subcategorias_Home2;
        
        lbMateria.setVisible(false);
        cbMateria.setVisible(false);
        
        lbCategoria.setVisible(false);
        cbCategoria.setVisible(false);
        
        inicioCBS();
        setarCBMateria();        
    }
    
    private void inicioCBS(){        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );         
            Color c = new Color( 255, 255, 255 );
        
            cbMateria     .setBackground( c );
            cbCategoria   .setBackground( c );          
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "inicioCBS(), \n"
                + e.getMessage() + "\n", "Menu_Pesquisa_Subcategorias" ); } } }.start();       
    }
    
    public void tabela(Tabela_Pesquisa_BD_Subcategorias Tabela_Pesquisa_BD_Subcategorias2){ 
                
        try {                
            Tabela_Pesquisa_BD_Subcategorias = Tabela_Pesquisa_BD_Subcategorias2;                                    
        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "tabela, \n"
                + e.getMessage() + "\n", "Menu_Pesquisa_Subcategorias" ); }     
    }
                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cbtipoP = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbMateria = new javax.swing.JComboBox();
        lbMateria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox();
        lbCategoria = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        tfPesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btExcluir = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados da subcategoria");

        jPanel5.setBackground(new java.awt.Color(253, 254, 247));

        jPanel6.setBackground(new java.awt.Color(253, 254, 247));

        cbtipoP.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbtipoP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "NOME", "NOME E MATÉRIA", "MATÉRIA E CATEGORIA" }));
        cbtipoP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbtipoP.setPreferredSize(new java.awt.Dimension(190, 24));
        cbtipoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoPActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Pesquisar por:");

        cbMateria.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbMateria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbMateria.setPreferredSize(new java.awt.Dimension(190, 24));
        cbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriaActionPerformed(evt);
            }
        });

        lbMateria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbMateria.setText("Matéria");

        cbCategoria.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbCategoria.setPreferredSize(new java.awt.Dimension(190, 24));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        lbCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCategoria.setText("Categoria");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbtipoP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbtipoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(lbCategoria)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(lbMateria)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbMateria, cbtipoP});

        jPanel1.setBackground(new java.awt.Color(253, 254, 247));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/exluir.gif"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.setPreferredSize(new java.awt.Dimension(97, 25));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/olho.png"))); // NOI18N
        btVisualizar.setText("Visualizar");
        btVisualizar.setEnabled(false);
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/alterar.gif"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.setPreferredSize(new java.awt.Dimension(97, 27));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btVisualizar)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btExcluir, btVisualizar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAlterar, btVisualizar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased
        pesquisar();
    }//GEN-LAST:event_tfPesquisaKeyReleased

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        pesquisar();  
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
             alterarOuVisualizar( "Alterar" );    
        } catch( Exception e ){      } } }.start();  
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
             alterarOuVisualizar( "Visualizar" );  
        } catch( Exception e ){      } } }.start();
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void cbtipoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoPActionPerformed
        try{
            //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
            //BookInfoMateria obj = (BookInfoMateria) cbMateria.getSelectedItem();
            //System.out.println( "obj.ID "+obj.ID );
            String op = cbtipoP.getSelectedItem().toString().trim();
            if( op.equals("NOME E MATÉRIA") ) {
                lbMateria.setVisible(true);
                cbMateria.setVisible(true);
                
                lbCategoria.setVisible(false);
                cbCategoria.setVisible(false);
                pesquisar(); 
            }
            else if( op.equals("MATÉRIA E CATEGORIA") ) {
                lbMateria.setVisible(true);
                cbMateria.setVisible(true);
                
                lbCategoria.setVisible(true);
                cbCategoria.setVisible(true);
                pesquisar(); 
            }
            else{
                
                lbMateria.setVisible(false);
                cbMateria.setVisible(false);
                
                lbCategoria.setVisible(false);
                cbCategoria.setVisible(false);
                pesquisar(); 
            }
        }
        catch( Exception e ){}
    }//GEN-LAST:event_cbtipoPActionPerformed

    private void cbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriaActionPerformed
        setarCBCategoria();
        pesquisar();
    }//GEN-LAST:event_cbMateriaActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        pesquisar();
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void pesquisar() {       
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            Query q = null;
            
            String tf = "";
            if( !tfPesquisa.getText().trim().equals("") ){
                tf = tfPesquisa.getText().trim().toUpperCase();
            }
            
            String op = cbtipoP.getSelectedItem().toString().trim();
            if( op.equals("TODOS") ) {
                q = JPAUtil.em().createNativeQuery("SELECT * FROM SCHEMAJMARY.SUBCATEGORIA WHERE SUBCATEGORIA LIKE ?", subcategoria.Subcategoria.class );
                q.setParameter(1, "%"+tf+"%");
            }
            else if( op.equals("NOME") ) {
                q = JPAUtil.em().createNativeQuery("SELECT * FROM SCHEMAJMARY.SUBCATEGORIA WHERE SUBCATEGORIA LIKE ?", subcategoria.Subcategoria.class );
                q.setParameter(1, "%"+tf+"%");
            } 
            else if( op.equals("NOME E MATÉRIA") ) {
                BookInfoMateria obj = (BookInfoMateria) cbMateria.getSelectedItem();
                
                q = JPAUtil.em().createNativeQuery("SELECT * FROM SCHEMAJMARY.SUBCATEGORIA WHERE SUBCATEGORIA LIKE ? AND ID_MATERIA = ?", subcategoria.Subcategoria.class );
                q.setParameter(1, "%"+tf+"%");
                q.setParameter(2, obj.ID ); 
            }   
            else if( op.equals("MATÉRIA E CATEGORIA") ) {
                BookInfoMateria   obj = (BookInfoMateria) cbMateria.getSelectedItem();
                BookInfoCategoria obj2 = (BookInfoCategoria) cbCategoria.getSelectedItem();
                
                q = JPAUtil.em().createNativeQuery("SELECT * FROM SCHEMAJMARY.SUBCATEGORIA WHERE SUBCATEGORIA LIKE ? AND ID_MATERIA = ? AND ID_CATEGORIA = ?", subcategoria.Subcategoria.class );
                q.setParameter(1, "%"+tf+"%");
                q.setParameter(2, obj.ID ); 
                q.setParameter(3, obj2.ID ); 
            }  
            
            if(q != null) { Tabela_Pesquisa_BD_Subcategorias.pesquisa(q); }
                        
        } catch( Exception e ){ /*JOPM JOPM = new JOPM( 2, "vPesquisar(), \n"
                + e.getMessage() + "\n", "Menu_Pesquisa_Subcategorias" );*/ } } }.start(); 
    }
    
    private void excluir() {  
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            if( btExcluir.isEnabled() ) {
            
                if( IDSELECIONADA > 0 ) {
                    
                    String excluir = "DELETE FROM SCHEMAJMARY.SUBCATEGORIA WHERE ID = ?";
                    
                    DB DB = new DB();
                    Connection con = DB.derby(); //con.close();
                    PreparedStatement pstm;
                    pstm = con.prepareStatement(excluir);
                    pstm.setInt( 1, IDSELECIONADA );
                    pstm.executeUpdate();
                    
                    con.close();
 
                    botoesEstado(false, false, false);
                    pesquisar();
                }
                else{
                    JOPM JOptionPaneMod = new JOPM( 2, "ID SELECIONADA, "
                            + "\nNenhuma categoria selecionada"
                            + "\nSelecione uma categoria"
                            + "\n", "Categoria selecionada" );
                
                    tfPesquisa.requestFocus();
                }
            }
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "excluir(), \n"
                + e.getMessage() + "\n", "Menu_Pesquisa_Categorias" ); } } }.start(); 
    }
    
    private void alterarOuVisualizar(String str) { 
        try{             
            if( btAlterar.isEnabled() ) {            
                if( IDSELECIONADA > 0 ) {
                    
                    Subcategoria Subcategoria = new Subcategoria();
                    
                    Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.SUBCATEGORIA WHERE ID = ?", Subcategoria.class );
                    q.setParameter(1, IDSELECIONADA);                      
                    List<subcategoria.Subcategoria> list = q.getResultList();
                    
                    for (int i = 0; i < list.size(); i++){ Subcategoria = list.get(i); }
                    
                    if( str.equals( "Visualizar") ){
                        
                        Subcategorias_New New = new Subcategorias_New( Subcategorias_Home, Subcategoria );
                        Subcategorias_Home.Home.ControleTabs.AddTabSemControleNovo( Subcategorias_Home.tabHome, "Visualizar", "/utilidades_imagens/olho.png", New );
                        New.btSalvar   .setVisible(false);
                        New.btAtualizar.setVisible(false);
                    }
                    else if( str.equals( "Alterar") ){
                        
                        Subcategorias_New New = new Subcategorias_New( Subcategorias_Home, Subcategoria );
                        Subcategorias_Home.Home.ControleTabs.AddTabSemControleNovo( Subcategorias_Home.tabHome, "Alterar", "/utilidades_imagens/alterar.gif", New );
                    }
                }
                else{
                    JOPM JOPM2 = new JOPM( "MÉTODO: " + "alterarOuVisualizar(String str)\n"
                        ,"\nID SELECIONADA:"
                        +"\nNenhuma subcategoria selecionada"
                        +"\nSelecione uma subcategoria" 
                        ,this.getClass().getName()
                    );
                    tfPesquisa.requestFocus();
                }
            }
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "alterar(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } //} }.start(); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAlterar;
    public javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisar;
    public javax.swing.JButton btVisualizar;
    public javax.swing.JComboBox cbCategoria;
    public javax.swing.JComboBox cbMateria;
    public javax.swing.JComboBox cbtipoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbMateria;
    public static javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
    
    boolean a, ex, v;
    public void botoesEstado(boolean a2, boolean ex2, boolean v2){      
        a = a2; ex = ex2; v = v2;
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
                    
            if( Bean_Usuario_Logado.ALTERARMATERIA == true ) { btAlterar   .setEnabled(a);  }
            if( Bean_Usuario_Logado.EXCLUIRMATERIA == true ) { btExcluir   .setEnabled(ex); }
            btVisualizar.setEnabled(v); 
                                    
        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "botoesEstado(boolean a2, boolean ex2, boolean v2), \n"
                + e.getMessage() + "\n", "Menu_Pesquisa_Categorias" ); } } }.start();     
    }
    
    //setar CB Matéria
   private void setarCBMateria() {       
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 

            Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.MATERIA WHERE MATERIA LIKE ?", materias.Materia.class );
            q.setParameter(1, "%"+""+"%");            
            List<materias.Materia> list = q.getResultList();
            
            if( cbMateria.getItemCount() > 0 ) { cbMateria.removeAllItems(); }
            
            for (int i = 0; i < list.size(); i++){ 
                cbMateria.addItem( new BookInfoMateria( 
                    list.get(i).getId(),list.get(i).getMateria()
                    )
                );    
            }
            
            setarCBCategoria();
                        
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarCBMateria(), \n"
                + e.getMessage() + "\n", "Menu_Pesquisa_Subcategorias" ); } } }.start(); 
    }
   
   //setar CB Categoria
   private void setarCBCategoria() {       
        //new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 

        if( cbMateria.getItemCount() > 0 ) {
            BookInfoMateria obj = (BookInfoMateria) cbMateria.getSelectedItem();
            
            Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.CATEGORIA WHERE ID_MATERIA = ?", categorias.Categoria.class );
            q.setParameter(1, obj.ID );            
            List<categorias.Categoria> list = q.getResultList();
            
            if( cbCategoria.getItemCount() > 0 ) { cbCategoria.removeAllItems(); }
            
            for (int i = 0; i < list.size(); i++){ 
                cbCategoria.addItem( new BookInfoCategoria( 
                    list.get(i).getId(),list.get(i).getCategoria()
                    )
                );    
            }
        }
                        
        //} catch( Exception e ){ JOPM JOPM = new JOPM( 2, "setarCBCategoria(), \n"
        //        + e.getMessage() + "\n", "Menu_Pesquisa_Subcategorias" ); } } }.start(); 
    }
    
}
