/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jmary.home;

import sistema.Sistema_Home;
import home_controle.AbrirTabInicial;
import home_controle.ControleTabs;
import java.awt.BorderLayout;
import javafx.application.Platform;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import utilidades.JOPM;

/**
 *
 * @author AnaMariana
 */
public class Home extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    
    public ControleTabs ControleTabs = new ControleTabs( this );
    public AbrirTabInicial AbrirTabInicial = new AbrirTabInicial( this );

    /**
     * Creates new form PnHomeDesigner
     */
    public Home() {
        initComponents();
        ((BasicInternalFrameUI)Home_Frame_Interno.getUI()).setNorthPane(null); //retirar o painel superior
        Home_Frame_Interno.setBorder( new EmptyBorder( 0, 0, 0, 0 ) );
                        
        Home_JPanel_Norte.setLayout( new BorderLayout() );
        
        AbrirTabInicial.inicio();
        
        inicio();        
    }
    
    private void inicio(){
        
        Sistema_Home Sistema_Home = new Sistema_Home( this );
        Home_JPanel_Centro.requestFocus();
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
        
            Platform.setImplicitExit(false);  
      
            /*String endereco_db     = System.getProperty("user.dir") + System.getProperty("file.separator") + "JMarySystems";  
            ControleThread_db t1 = new ControleThread_db( endereco_db );         
            t1.setName("ControleThread_db");           
            t1.start(); */
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "inicio(), \n"
                + e.getMessage() + "\n", "Home" ); } } }.start(); 
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home_Frame_Interno = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        Home_JPanel_Centro = new javax.swing.JPanel();
        tabHome = new javax.swing.JTabbedPane();
        Home_JPanel_Norte = new javax.swing.JPanel();
        Home_Barra_Menu = new javax.swing.JMenuBar();
        menu_Ajuda = new javax.swing.JMenu();

        Home_Frame_Interno.setBorder(null);
        Home_Frame_Interno.setVisible(true);

        javax.swing.GroupLayout Home_JPanel_NorteLayout = new javax.swing.GroupLayout(Home_JPanel_Norte);
        Home_JPanel_Norte.setLayout(Home_JPanel_NorteLayout);
        Home_JPanel_NorteLayout.setHorizontalGroup(
            Home_JPanel_NorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Home_JPanel_NorteLayout.setVerticalGroup(
            Home_JPanel_NorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Home_JPanel_CentroLayout = new javax.swing.GroupLayout(Home_JPanel_Centro);
        Home_JPanel_Centro.setLayout(Home_JPanel_CentroLayout);
        Home_JPanel_CentroLayout.setHorizontalGroup(
            Home_JPanel_CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabHome, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(Home_JPanel_Norte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Home_JPanel_CentroLayout.setVerticalGroup(
            Home_JPanel_CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home_JPanel_CentroLayout.createSequentialGroup()
                .addComponent(Home_JPanel_Norte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabHome, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home_JPanel_Centro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home_JPanel_Centro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu_Ajuda.setText("Ajuda");
        Home_Barra_Menu.add(menu_Ajuda);

        Home_Frame_Interno.setJMenuBar(Home_Barra_Menu);

        javax.swing.GroupLayout Home_Frame_InternoLayout = new javax.swing.GroupLayout(Home_Frame_Interno.getContentPane());
        Home_Frame_Interno.getContentPane().setLayout(Home_Frame_InternoLayout);
        Home_Frame_InternoLayout.setHorizontalGroup(
            Home_Frame_InternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Home_Frame_InternoLayout.setVerticalGroup(
            Home_Frame_InternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home_Frame_Interno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home_Frame_Interno)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Home_Barra_Menu;
    public javax.swing.JInternalFrame Home_Frame_Interno;
    public javax.swing.JPanel Home_JPanel_Centro;
    public javax.swing.JPanel Home_JPanel_Norte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu_Ajuda;
    public javax.swing.JTabbedPane tabHome;
    // End of variables declaration//GEN-END:variables
            
}
